Feature/follow apis
webdonalds/YAS-backend pull request #69
Opened 2021-07-18 13:03 UTC by hywook4

2021-07-24 09:32 UTC, zych1751 requested changes

2021-07-24 09:32 UTC, zych1751 commented on docs/yas_api_follow_doc.md
> +| videoId     | VIDEO_ID         | O        |
videoId는 왜 필요한가요?

2021-07-24 09:32 UTC, zych1751 commented on docs/yas_api_follow_doc.md
> +## GET - /v1/follow/followeesByFollower/{followerId}
RESTful하게 짜는거라면 resource는 그냥 follow가 되는게 맞아보이고, 필터가 필요한 부분은 url parameter으로 받는게 맞아보입니다.
```
GET /v1/follow?followerId={follwerId}
GET /v1/follow?followeeId={follweeId}
```

2021-07-24 09:32 UTC, zych1751 commented on src/api/index.ts
>  export default router;
newline을 추가해주세요!
매번 추가하기 귀찮다면, 에디터에서 셋팅해주세요.
vscode를 사용한다면 Preference > Settings > Files: Insert Final Newline 에서 셋팅할 수 있어요.

2021-07-24 09:32 UTC, zych1751 commented on src/api/v1/follow.ts
> +    }
indent가 이상해요 ㅠㅠ

2021-07-24 09:32 UTC, zych1751 commented on src/api/v1/follow.ts
> +        include: includeOptions
lastFollowId가 있는 경우와 없는 경우가 where문만 다른것 같아서 코드를 좀 더 깔끔하게 짤 수 있어요.

Sequelize가 id가 null인 경우에 없는 것으로 해석한다면, where/id값을 삼항연산자로 처리해도 될 것 같고, 아니면 where 옵션만 includeOptions처럼 변수화 할 수도 있겠네요.

2021-07-24 09:32 UTC, zych1751 commented on src/api/v1/follow.ts
> +  }
인덱스가 굳이 필요한게 아니면 forEach를 써도 좋아보입니다.

2021-07-24 09:32 UTC, zych1751 commented on src/api/v1/follow.ts
> +  const followerId = request.params.followerId;
이 값에 대한 validate가 필요해 보여요.

2021-07-24 09:32 UTC, zych1751 commented on src/model/Follow.ts
> +export default Follow;
여기도 newline

2021-07-24 09:32 UTC, zych1751 commented on src/model/index.ts
> +    },
logging을 없앤 이유가 있을까요?

2021-07-25 05:23 UTC, hywook4 commented
follow 정보에서 userId 빼기 (불필요한 정보)

2021-07-27 16:04 UTC, hywook4 commented on src/api/v1/follow.ts
> +        include: includeOptions
null인 경우로 체크를 하기때문에 그대로 진행하겠씁니다.

2021-07-27 16:19 UTC, hywook4 commented on src/api/v1/follow.ts
> +        include: includeOptions
새로운 방법을 찾아서 간결하게 고쳤습니다

2021-07-27 16:30 UTC, hywook4 commented on docs/yas_api_follow_doc.md
> +## GET - /v1/follow/followeesByFollower/{followerId}
수정완료

2021-07-27 16:30 UTC, hywook4 commented on src/api/index.ts
>  export default router;
적용완료

2021-07-27 16:31 UTC, hywook4 commented on src/api/v1/follow.ts
> +    }
코드 지워짐

2021-07-27 16:31 UTC, hywook4 commented on src/api/v1/follow.ts
> +  }
수정하였습니다

2021-08-08 10:56 UTC, zych1751 requested changes
해결이 된 conversation 에 대해서는 resolve를 눌러주시고, 새로 리뷰를 요청할 때, re-request review를 눌러서 확인할 수 있게 해주세요!

2021-08-08 10:56 UTC, zych1751 commented on src/api/v1/follow.ts
> +    };
```suggestion
    whereOption["id"] = { [Op.lt]: lastFollowId } 
```
과도한 ... 사용인것 같아요.

2021-08-08 10:56 UTC, zych1751 commented on src/api/v1/follow.ts
> +  let target;
이건 굳이 고칠필요는 없겠지만, const로 하고 삼항연산자로 대입해도 괜찮을듯 해요.
값이 설정되고 난 이후에 바뀔 이유가 없어보여서요.

2021-08-08 10:56 UTC, zych1751 commented on src/api/v1/follow.ts
> +  }
if에 followerId로만 체크하는것 보다는 null 혹은 undefined 등으로 체크하는게 좋을 것 같고, 이미 둘 중 하나의 값이 있는것은 보장되어 있으니 else if 보다는 else가 좋아보여요.

2021-08-08 10:56 UTC, zych1751 commented on src/api/v1/follow.ts
> +  result.forEach(data => follows.push(data.dataValues[target]));
```suggestion
  const follows = result.map(data => data.dataValues[target]);
```

2021-08-08 10:56 UTC, zych1751 commented on src/api/v1/follow.ts
> +    return ;
띄워쓰기 없어도 될 것 같네요.

2021-08-08 10:56 UTC, zych1751 commented on src/model/index.ts
> +// initialize models
전체적으로 띄워쓰기가 좀 많은 것 같아요 ㅠㅠ
적당한 띄워쓰기는 코드를 보기 좋게 하지만 너무 많은 띄워쓰기는 위아래로 코드가 길어져서 오히려 보기 힘들어져요.

2021-08-08 13:49 UTC, hywook4 commented on src/api/v1/follow.ts
> +  }
follower이나 followee가 0인 경우를 대비하여 그렇게 수정하도록 하였습니다.

2021-08-08 14:02 UTC, zych1751 approved these changes

2021-08-08 14:03 UTC, merged