리팩토링 및 린트 수정
webdonalds/YAS-backend pull request #73
Opened 2021-07-25 05:46 UTC by zych1751

resolves #68 

1. api 별로 dto를 만듬.
 - db 정보를 그대로 내릴 때, 민감 정보가 내려가는 경우도 있었음. (google refresh token)
2. video API 수정/삭제의 경우에도 아이디를 리턴하게 수정
3. 전체적인 리팩토링
4. 린트 및 에러가 나던 것들 수정
5. `npm run test` -> `npm run start`

2021-08-11 15:24 UTC, hywook4 requested changes
POST나 DELETE같은 API에서 response 형태가 바뀐것들은 문서에 변경점 반영해주세요

2021-08-11 15:24 UTC, hywook4 commented on src/api/v1/auth.ts
> +        response.json(accessTokenResponse);
이건 바꿀 필요는 없지만, 
아예 response 를 주는 객체에 커스텀 타입을 정의할 수 있는 것 같습니다. (다만 짧게 찾아본바로는 생각만큼깔끔하게는 있는지 모르겠네요)
아무튼 만약 response: express.Response 부분에서 Response 타입을 커스텀해서 사용이 가능한것같네요.
TMI 입니다.
https://stackoverflow.com/questions/64601286/specify-a-type-for-response-express

2021-08-11 15:24 UTC, hywook4 commented on src/api/v1/user.ts
> +    response.json();
앞으로 성공에 대한 response는 empty message로 하고 200으로만 판별한다고 생각해도 될까요?

2021-08-16 07:45 UTC, zych1751 commented on src/api/v1/user.ts
> +    response.json();
:ok_hand:

2021-08-16 08:32 UTC, zych1751 commented on src/api/v1/auth.ts
> +        response.json(accessTokenResponse);
넵. 여기서 하기엔 너무 길어질것 같아서 다음에 처리하고 우선 이 PR은 여기서 끝내면 좋을 것 같아요.

2021-08-16 14:22 UTC, hywook4 approved these changes

2021-08-16 14:22 UTC, merged